/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Game engine");
  view1 = new GView(this, 266, 0, 1333, 673, JAVA2D);
  panel1 = new GPanel(this, 0, 0, 266, 673, "Main______________________________________");
  panel1.setCollapsed(true);
  panel1.setDraggable(false);
  panel1.setText("Main______________________________________");
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  panel2 = new GPanel(this, 0, 19, 266, 654, "");
  panel2.setCollapsible(false);
  panel2.setDraggable(false);
  panel2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  panel2.setOpaque(false);
  panel2.addEventHandler(this, "panel2_Click1");
  panel5 = new GPanel(this, 0, 11, 266, 169, "Collisions");
  panel5.setText("Collisions");
  panel5.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  panel5.setOpaque(true);
  panel5.addEventHandler(this, "panel5_Click1");
  panel6 = new GPanel(this, 0, 189, 266, 200, "Camera");
  panel6.setText("Camera");
  panel6.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  panel6.setOpaque(true);
  panel6.addEventHandler(this, "panel6_Click1");
  button3 = new GButton(this, 3, 25, 260, 15);
  button3.setText("Reset la camera");
  button3.addEventHandler(this, "button3_click1");
  CamX = new GTextField(this, 3, 85, 260, 20, G4P.SCROLLBARS_NONE);
  CamX.setPromptText("Position_camera_X");
  CamX.setOpaque(true);
  CamX.addEventHandler(this, "CamX_change1");
  CamY = new GTextField(this, 3, 110, 260, 20, G4P.SCROLLBARS_NONE);
  CamY.setPromptText("Position_camera_Y");
  CamY.setOpaque(true);
  CamY.addEventHandler(this, "CamY_change1");
  camZoom = new GTextField(this, 3, 170, 260, 20, G4P.SCROLLBARS_NONE);
  camZoom.setPromptText("Zoom_Camera_(std:1)");
  camZoom.setOpaque(true);
  camZoom.addEventHandler(this, "camZoom_change1");
  button1 = new GButton(this, 3, 45, 260, 15);
  button1.setText("Centrer sur X");
  button1.addEventHandler(this, "centerCamX_click1");
  centerCamY = new GButton(this, 3, 65, 260, 15);
  centerCamY.setText("Centrer sur Y");
  centerCamY.addEventHandler(this, "centerCamY_click1");
  label5 = new GLabel(this, 0, 145, 266, 20);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Zoom de la caméra");
  label5.setOpaque(true);
  panel6.addControl(button3);
  panel6.addControl(CamX);
  panel6.addControl(CamY);
  panel6.addControl(camZoom);
  panel6.addControl(button1);
  panel6.addControl(centerCamY);
  panel6.addControl(label5);
  panel2.addControl(panel5);
  panel2.addControl(panel6);
  panel1.addControl(panel2);
  panel4 = new GPanel(this, 0, 673, 1598, 229, "Tab bar text");
  panel4.setCollapsible(false);
  panel4.setDraggable(false);
  panel4.setText("Tab bar text");
  panel4.setOpaque(true);
  panel4.addEventHandler(this, "panel4_Click1");
  panel7 = new GPanel(this, 267, -23, 313, 242, "Variables internes");
  panel7.setDraggable(false);
  panel7.setText("Variables internes");
  panel7.setOpaque(false);
  panel7.addEventHandler(this, "panel7_Click1");
  label1 = new GLabel(this, 5, 25, 300, 20);
  label1.setText("Mouse position :");
  label1.setOpaque(false);
  wordpos = new GLabel(this, 5, 45, 300, 40);
  wordpos.setTextAlign(GAlign.TOP, GAlign.TOP);
  wordpos.setText("Position du monde :");
  wordpos.setOpaque(false);
  zoomView = new GLabel(this, 5, 85, 300, 20);
  zoomView.setText("Zoom vue :");
  zoomView.setOpaque(false);
  panel7.addControl(label1);
  panel7.addControl(wordpos);
  panel7.addControl(zoomView);
  panel8 = new GPanel(this, 0, 19, 266, 653, "Parametres________________________________");
  panel8.setCollapsed(true);
  panel8.setDraggable(false);
  panel8.setText("Parametres________________________________");
  panel8.setLocalColorScheme(GCScheme.RED_SCHEME);
  panel8.setOpaque(true);
  panel8.addEventHandler(this, "panel8_Click1");
  internVar = new GCheckbox(this, 0, 50, 266, 20);
  internVar.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  internVar.setText("Afficher les variables internes");
  internVar.setOpaque(false);
  internVar.addEventHandler(this, "internVar_clicked1");
  internVar.setSelected(true);
  internvarop = new GCheckbox(this, 0, 70, 266, 20);
  internvarop.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  internvarop.setText("Fond des variables internes");
  internvarop.setOpaque(false);
  internvarop.addEventHandler(this, "internvarop_clicked1");
  label2 = new GLabel(this, 0, 30, 266, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Afficheur de variable");
  label2.setLocalColorScheme(GCScheme.RED_SCHEME);
  label2.setOpaque(true);
  label3 = new GLabel(this, 0, 110, 266, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Fenetres");
  label3.setLocalColorScheme(GCScheme.RED_SCHEME);
  label3.setOpaque(true);
  Resetint = new GButton(this, 8, 140, 250, 20);
  Resetint.setText("Reset l'interface");
  Resetint.setLocalColorScheme(GCScheme.RED_SCHEME);
  Resetint.addEventHandler(this, "Resetint_click1");
  label4 = new GLabel(this, 0, 180, 266, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Vue");
  label4.setLocalColorScheme(GCScheme.RED_SCHEME);
  label4.setOpaque(true);
  panel8.addControl(internVar);
  panel8.addControl(internvarop);
  panel8.addControl(label2);
  panel8.addControl(label3);
  panel8.addControl(Resetint);
  panel8.addControl(label4);
}

// Variable declarations 
// autogenerated do not edit
GView view1; 
GPanel panel1; 
GPanel panel2; 
GPanel panel5; 
GPanel panel6; 
GButton button3; 
GTextField CamX; 
GTextField CamY; 
GTextField camZoom; 
GButton button1; 
GButton centerCamY; 
GLabel label5; 
GPanel panel4; 
GPanel panel7; 
GLabel label1; 
GLabel wordpos; 
GLabel zoomView; 
GPanel panel8; 
GCheckbox internVar; 
GCheckbox internvarop; 
GLabel label2; 
GLabel label3; 
GButton Resetint; 
GLabel label4; 
